# Generated by Django 4.0.1 on 2022-10-17 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Titulo')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Dt. Atualização')),
                ('sumary', models.TextField(max_length=300, verbose_name='Resumo')),
                ('content', models.TextField(verbose_name='Postagem')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Criação')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, verbose_name='Status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
